version: '3.8'

services:
  kong-database:
    image: arm64v8/postgres:11
    container_name: kong-database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data-kong-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - kong-net

  konga-db-creator:
    image: arm64v8/postgres:11
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPASSWORD=${POSTGRES_PASSWORD}
    entrypoint: >
      bash -c "
        # Wait until the DB is ready
        until pg_isready -h kong-database -U ${POSTGRES_USER}; do
          sleep 2;
        done;
        # Check if the Konga DB exists, create it if not
        psql -h kong-database -U ${POSTGRES_USER} -tc \"SELECT 1 FROM pg_database WHERE datname = '${KONGA_DB}'\" | grep -q 1 ||
        psql -h kong-database -U ${POSTGRES_USER} -c \"CREATE DATABASE \\\"${KONGA_DB}\\\"\";
      "
    networks:
      - kong-net
    restart: "no"

  kong-migrations:
    image: kong:3.6.1
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=${POSTGRES_USER}
      - KONG_PG_PASSWORD=${POSTGRES_PASSWORD}
      - KONG_PG_DATABASE=${POSTGRES_DB}
    command: kong migrations bootstrap
    networks:
      - kong-net
    restart: "no"

  kong:
    image: kong:3.6.1
    container_name: kong
    depends_on:
      - kong-migrations
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=${POSTGRES_USER}
      - KONG_PG_PASSWORD=${POSTGRES_PASSWORD}
      - KONG_PG_DATABASE=${POSTGRES_DB}
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://displate-gateway-admin.dev.displate.top
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_LOG_LEVEL=debug
      - STORES_API_KEY=${STORES_API_KEY}
      - PRODUCTS_API_KEY=${PRODUCTS_API_KEY}
      - MENUS_API_KEY=${MENUS_API_KEY}
      - COMPANIES_API_KEY=${COMPANIES_API_KEY}
      - USERS_API_KEY=${USERS_API_KEY}
      # --- START OF CUSTOM PLUGIN ADDITIONS ---
      - KONG_PLUGINS=bundled,jwt-user-header # <--- Enable your custom plugin
      # Explicitly set Lua path to include our custom plugin location AND all of Kong's default paths.
      # This prevents hiding Kong's core files.
      - KONG_LUA_PATH=/opt/custom_lua/?.lua;/opt/custom_lua/?/init.lua;./?.lua;/usr/local/openresty/luajit/share/luajit-2.1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/openresty/luajit/share/lua/5.1/?.lua;/usr/local/openresty/luajit/share/lua/5.1/?/init.lua
      # --- END OF CUSTOM PLUGIN ADDITIONS ---
    networks:
      - kong-net
    command: ["sleep", "infinity"] # <--- TEMPORARY: Keep container running for debugging
    restart: "no" 
    volumes:
      # --- START OF CUSTOM PLUGIN VOLUME MOUNT ---
      # Mount your host directory with the 'kong/plugins' structure
      # into a NEW, custom directory in the container.
      - ./kong_custom_mount_root:/opt/custom_lua/
      # --- END OF CUSTOM PLUGIN VOLUME MOUNT ---

  konga:
    image: packyzbq/konga:0.14.9-arm64
    container_name: konga
    depends_on:
      - konga-db-creator
    environment:
      - NODE_ENV=development
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE=${KONGA_DB}
      - KONGA_HOOK_TIMEOUT=120000
      - KONGA_KONG_URL=http://kong:8001
    networks:
      - kong-net
    restart: on-failure

volumes:
  db-data-kong-postgres:

networks:
  kong-net:
    driver: bridge